### ISSUE TITLE
Variable in CWrkWriteThread::Entry() uninitialized

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp#102]
Line 538, The variable event is never initialized but used later on.

**Comment by grodansparadis** [comment]
File please!

**Comment by BlueAndi** [comment]
vscp_software\src\vscp\drivers\level2\rawethernet\linux\vscpl2drv_raweth.cpp

**Comment by grodansparadis** [comment]
Not an issue anymore
