### ISSUE TITLE
Nickname discovery feature request for daemon

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp#125]
The daemon already has some segment master features, like the segment controller heartbeat.
Only the nickname discovery feature is missing to get a complete segment master.

The advantage with the nickname discovery is, that the daemon always know the nodes. This kind of information could be used in the internal webinterface too.

**Comment by grodansparadis** [comment]
Yes this is in the plan. Needed to have "named nodes" in the future and other good things.

**Comment by BlueAndi** [comment]
Named nodes sounds good and I feel it will go more in the direction of wizards or node organization.

**Comment by grodansparadis** [comment]
This is implemented in 15.0 that collects node info to a db.
