### ISSUE TITLE
feature request: read and display strings in vscpworks dev.conf.window abstraction view

### ISSUE THREAD

**Issue by datenheim** [grodansparadis/vscp#150]
It would be very straight forward to have works able to read and present strings also in the device configuration window view - just as it already does with other values.
![devcfgabstr](https://cloud.githubusercontent.com/assets/101634/8155492/1cb995be-1345-11e5-9ca7-4b3ed216e94b.jpg)

**Comment by grodansparadis** [comment]
I thought that was working. Will have a look.

Stefan Langer skrev den 2015-06-15 09:59:
>
> It would be very straight forward to have works able to read and 
> present strings also in the device configuration window view - just as 
> it already does with other values.
> devcfgabstr 
> <https://cloud.githubusercontent.com/assets/101634/8155492/1cb995be-1345-11e5-9ca7-4b3ed216e94b.jpg>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/150>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by grodansparadis** [comment]
VSCP Works is deprecated

**Comment by grodansparadis** [comment]
VSCP Works is deprecated
