### ISSUE TITLE
Wesocket feature: Variable shall be sent automatically onChange / onCreate / onRemoved

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp#162]
Instead of polling a variable, it would be better to be notified about a new variable, a removed variable and in case a variable value changed.

I thought about a subscribe mechanism for every variable.

Advantage:
- Easier implementation on client side
- Less communication load
- Less latency, therefore better usability ... the user see the change not a second later

**Comment by grodansparadis** [comment]
Yes agree. This was actually in the first version but I lacked the time 
to implement. Will do this.

Den 2015-07-21 kl. 13:25, skrev Andreas Merkle:
>
> Instead of polling a variable, it would be better to be notified about 
> a new variable, a removed variable and in case a variable value changed.
>
> I thought about a subscribe mechanism for every variable.
>
> Advantage:
>
>   * Easier implementation on client side
>   * Less communication load
>   * Less latency, therefore better usability ... the user see the
>     change not a second later
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/162>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by grodansparadis** [comment]
No tvalid anymore but will maybe come in a driver
