### ISSUE TITLE
Standardizes websocket GT and LISTVAR

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp#164]
LISTVAR return every variable with +;LiSTVAR;.... but didn't notfiy about how many variables will follow.
GT return every table row with +;TR; .... and +;GT;XXX notify about how many table rows will follow.

It would be good to standardize the behavior of them and future commands.

I prefer the approach of GT, because it is clear how many items will follow. Using LISTVAR, a timeout is necessary to determine the end of the list.

**Comment by grodansparadis** [comment]
Good. I will fix/change that.

Den 2015-07-24 kl. 15:23, skrev Andreas Merkle:
>
> LISTVAR return every variable with +;LiSTVAR;.... but didn't notfiy 
> about how many variables will follow.
> GT return every table row with +;TR; .... and +;GT;XXX notify about 
> how many table rows will follow.
>
> It would be good to standardize the behavior of them and future commands.
>
> I prefer the approach of GT, because it is clear how many items will 
> follow. Using LISTVAR, a timeout is necessary to determine the end of 
> the list.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/164>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by grodansparadis** [comment]
Should be fixed.
