### ISSUE TITLE
Interface Kodi

### ISSUE THREAD

**Issue by grodansparadis** [grodansparadis/vscp#176]
Interface to Kodi http://kodi.tv should be made

**Comment by BlueAndi** [comment]
and all other enigma2 plattforms :-)

**Comment by grodansparadis** [comment]
ha ha

Den 2015-09-04 kl. 18:46, skrev Andreas Merkle:
>
> and all other enigma2 plattforms :-)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/176#issuecomment-137788141>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by waaslandwolf** [comment]
I am running Kodi so I am watching this one. It is pretty low on my features priority list though.

**Comment by grodansparadis** [comment]
One day it will be done...
