### ISSUE TITLE
vscpd webserver seems not to start (sodium, debian wheezy)

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp#194]
/vscp folder is not accessible via port 8080
websocket is down too

the default configuration (vscp.conf) is used

the log files says "webserver is active"

tested on a beaglebone black, debian wheezy, libwxbase2.8-dev

**Comment by grodansparadis** [comment]
Anything in the logs?

Den 2015-10-27 kl. 22:50, skrev Andreas Merkle:
>
> /vscp folder is not accessible via port 8080
> websocket is down too
>
> the default configuration (vscp.conf) is used
>
> the log files says "webserver is active"
>
> tested on a beaglebone black, debian wheezy, libwxbase2.8-dev
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/194>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by grodansparadis** [comment]
Just tested with a fresh installation here and it looks like it work as 
it should.

Den 2015-10-27 kl. 22:50, skrev Andreas Merkle:
>
> /vscp folder is not accessible via port 8080
> websocket is down too
>
> the default configuration (vscp.conf) is used
>
> the log files says "webserver is active"
>
> tested on a beaglebone black, debian wheezy, libwxbase2.8-dev
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/194>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by BlueAndi** [comment]
Strange ... I just powered the beaglebone on again a minute ago, with same software as yesterday ... now it works here as well.

**Comment by grodansparadis** [comment]
Good to here. Could it be two daemons running at the same time?

Den 2015-10-28 kl. 21:41, skrev Andreas Merkle:
>
> Strange ... I just powered the beaglebone on again a minute ago, with 
> same software as yesterday ... now it works here as well.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/194#issuecomment-151984342>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by BlueAndi** [comment]
No. I stopped the daemon and checked it with
ps -Al | grep vscpd

**Comment by grodansparadis** [comment]
Strange then.

Den 2015-10-28 kl. 21:44, skrev Andreas Merkle:
>
> No. I stopped the daemon and checked it with
> ps -Al | grep vscpd
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/194#issuecomment-151985025>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by BlueAndi** [comment]
Same effect again ... still the same software.
Powered up the beaglebone and the webserver seems to be dead. No websocket available and etc.

What can I check now?

**Comment by grodansparadis** [comment]
Can it be something else on port 8080? Try to change it to something 
else on the daemon.

**Comment by grodansparadis** [comment]
old
