### ISSUE TITLE
RPi & Frankfurt daemon not woking

### ISSUE THREAD

**Issue by grodansparadis** [grodansparadis/vscp#196]
On rpi & Frankfurt it's a semi-success:

the canal interface works fine

through daemon it's weird: using vscpd -s  I can see the Frankfurt interface is opened.

when using works to see interfaces, Frankfurt isn't in the list. Same with web-interface.

git pull from yesterday.

**Comment by svenZ80** [comment]
more info:
interfaces ok, forgot to use sudo to restart daemon
I removed the simulation driver, and now daemon works fine with Frankfurt

**Comment by grodansparadis** [comment]
OK you added it here. Thanks! Perfect.

Den 2015-10-28 kl. 20:14, skrev svenZ80:
>
> more info:
> interfaces ok, forgot to use sudo to restart daemon
> I removed the simulation driver, and now daemon works fine with Frankfurt
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/196#issuecomment-151961267>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org
