### ISSUE TITLE
Add support for all measurements to vscp_getVSCPMeasurementAsString/vscp_getVSCPMeasurementAsDouble

### ISSUE THREAD

**Issue by grodansparadis** [grodansparadis/vscp#200]
vscp_getVSCPMeasurementAsString/vscp_getVSCPMeasurementAsDouble currently just support 

CLASS1.MEASUREMENT
CLASS2_LEVEL1.MEASUREMENT 
CLASS2_MEASUREMENT_FLOAT
CLASS2_MEASUREMENT_STR

support should be added for all measurement classes,

**Comment by dinguluer** [comment]
Nice ..!!

**Comment by grodansparadis** [comment]
IN 13.0
