### ISSUE TITLE
Add labels to VSCP Works client window

### ISSUE THREAD

**Issue by waaslandwolf** [grodansparadis/vscp#220]
The VSCP Works client window shows events as they are received on the bus. The following colums of information are shown:
- Direction (TX/RX)
- Class & Type
- Note (showing NodeID & GUID)

But the content of the event isn't shown in a clear way. One has to click on an event only to see some details appear in the window on the right. Even there the payload is only shown as HEX and DEC numbers which isn't easy to interpret. One has to know in the back of ones mind which zone and subzone numbers represent what in real-life, which nodeID is connected to what device in real life etc. 

Wouldn't it be cool if VSCP had a translation tabel that was able to cross-reference the HEX and DEC numbers to some real-life use case? 

For example; 
Nickname 10 = "Master bedroom 8-way button faceplate"
Zone 1 = "1st floor"
Subzone 253 = "Master bedroom button 8"
Index 8 = "button 8"

That way the client window (and the rest of the VSCP software suite) could represent a "CLASS1_INFORMATION, ON with data 0x08, 0x01, 0xFD" event as:
Master bedroom 8-way button faceplate; 1st floor, Master bedroom button 8, button 8

Much more useful, don't you agree? :-)

Happy coding!
David

**Comment by vscp** [comment]
Hi David. For some reason this was not sent to me so I just saw it now. Yes this will come.

**Comment by waaslandwolf** [comment]
Cool! I'm sure It will be much more user -friendly covering up All the hex codes ;-)

-----Oorspronkelijk bericht-----
Van: "Very Simple Control Protocol" <notifications@github.com>
Verzonden: ‎14/‎03/‎2017 22:12
Aan: "grodansparadis/vscp" <vscp@noreply.github.com>
CC: "waaslandwolf" <waaslandwolf@gmail.com>; "Author" <author@noreply.github.com>
Onderwerp: Re: [grodansparadis/vscp] Add labels to VSCP Works client window(#220)

Hi David. For some reason this was not sent to me so I just saw it now. Yes this will come.

**Comment by grodansparadis** [comment]
VSCP Works is deprecated
