### ISSUE TITLE
All events with same node ID

### ISSUE THREAD

**Issue by mamac** [grodansparadis/vscp#227]
In VSCPWORKS, in the event list, all events have the same node ID:
![image](https://user-images.githubusercontent.com/7148802/32630063-93b6ca32-c59b-11e7-862d-99cde355ca71.png)
I can't remember it was like this with previous versions.

I have about 20 nodes with different IDs.

**Comment by grodansparadis** [comment]
Yes that looks strange. Will check.
Is the data correct?

**Comment by mamac** [comment]
The data is not even correct, for example it receive a temperature message with value -73K, but in reality temperature is positive and sent in Celsius.
Also I cannot connect to nodes with the device configuration window, maybe it is related...

**Comment by grodansparadis** [comment]
Probably has to do with the timedate addition.  Sadly I can't check/fix  until Sunday.

**Comment by grodansparadis** [comment]
I tested this on my local systems and it works here as far as I can see. The upcoming release (head code) will not be backward compatible so client and servers need to update to major version 12.

**Comment by mamac** [comment]
OK, I need to update my server then :-)
