### ISSUE TITLE
CLASS1_PROTOCOL - PROTOCOL_GENERAL

### ISSUE THREAD

**Issue by waaslandwolf** [grodansparadis/vscp#229]
Open VSCP works 12.29.2.6 on Ubuntu
Open Client window
All events, even known good events such as CLASS1_PROTOCOL, HEARTBEAT events, show as CLASS1_PROTOCOL - PROTOCOL_GENERAL.

A previously known good, saved, txset that sends CLASS1_INFORMATION, BUTTON events now shows "Unknown class", "unknown type" event when sent.

**Comment by grodansparadis** [comment]
Open this again if it still is a problem in later versions.

**Comment by waaslandwolf** [comment]
I did a git pull and build 2 days ago and it can confirm that this problem still persists.

**Comment by grodansparadis** [comment]
Strange! I use it on a daily basis here.  Can you save received events and send to me. Also a screen dump would be fine.

**Comment by waaslandwolf** [comment]
Ok will do!

**Comment by grodansparadis** [comment]
I can't still repeat this behavior. Open if still there.
