### ISSUE TITLE
Please check remotevariable.cpp @ handleLoadVardata() function

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp#255]
Please check the following function, because I don't get it. ;-)
The variable tmp gets first malloced data and then tmp is overwritten again in the first if-condition.
And in the 2nd part of the if-condition, tmp content is overwritten, because the realloc goes on last_load_var_content, but not on tmp.

```
static void
handleLoadVardata(void *data, const char *content, int length)
{
    CVariableStorage *pStorage = (CVariableStorage *)data;
    if (NULL == data) return;

    int prevLength =
      (NULL == last_load_var_content) ? 0 : strlen(last_load_var_content);
    char *tmp = (char *)malloc(length + 1 + prevLength);
    strncpy(tmp, content, length);
    tmp[length] = '\0';

    if (NULL == last_load_var_content) {
        tmp = (char *)malloc(length + 1);
        strncpy(tmp, content, length);
        tmp[length]           = '\0';
        last_load_var_content = tmp;
    } else {
        // Concatenate
        int newlen            = length + 1 + strlen(last_load_var_content);
        last_load_var_content = (char *)realloc(last_load_var_content, newlen);
        strncat(tmp, content, length);
        last_load_var_content[newlen] = '\0';
    }
}
```
Additional check line 4123: ```id = vscp_readStringValue(vscp_str_left(str, pos));```
Because here the variable pos is used, but never initialized.

**Comment by grodansparadis** [comment]
Yes this is wrong. I think it is left like this in some other files also I think  but fixed in the dm XML read IIRC.  It's left because I plan to rewrite some stuff here anyway and because the variable format is

```xml
<variable type="boolean"
        name="VSCP_LEVEL_II_SIM_DRIVER_BLEVEL20"
        persistent="true"
        user="0"
        access-rights="0x644"
        value="ZmFsc2U="
        note="VGhpcyBpcyBub3QgYSBMZXZlbCBJSSBub2RlLg==" />
```

so there is no data thus should be removed. Thanks for the heads up.
