### ISSUE TITLE
Make areas in Device Configuration Window resizable

### ISSUE THREAD

**Issue by waaslandwolf** [grodansparadis/vscp#39]
Ake,

I have a feature request: the Device Configuration Window is divided into two main "areas": the receive area on the top, and the transmit area on the bottom. These area's are not resizable, which means that one cannot enlarge the receive area. When the whole window is resized, the transmit area is resize accordingly but the receive area is fixed.

I would like to be able to enlarge the receive area so that, when I select a receive line, I all properties in the area to the right of them fit. At the moment I can not see the "From GUID:" easily, I have to select the receive line and scroll down every time which is quite annoying. I have little interest in the send area (yet) so I would be happier if that were smaller and the receive area larger so all properties fit.

![syjoz2 8](https://cloud.githubusercontent.com/assets/6858464/5288024/ab588b06-7b31-11e4-8a47-0968d1428e02.PNG)

If it's not too much effort, would it be possible to allow the user to drag the division between the receive and transmit area?

Thanks in advance,
David.

**Comment by grodansparadis** [comment]
vscp works is deprecated
