### ISSUE TITLE
Protocol events with types greater than 39 are unknown by vscpworks

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp#96]
See example:
![unbenannt](https://cloud.githubusercontent.com/assets/9699465/6417550/75cf1ab6-beae-11e4-90bb-9304e650d7ea.JPG)

**Comment by BlueAndi** [comment]
As I see all strings are hardcoded in the source.
How about keeping them external in a xml file? They could be easy extended for everyone, e. g. someone defined own labratory or local class types.

Shall I make a proposal for xml format?

**Comment by grodansparadis** [comment]
That is a good suggestion.  Do that.

Andreas Merkle skrev den 2015-02-28 20:05:
>
> As I see all strings are hardcoded in the source.
> How about keeping them external in a xml file? They could be easy 
> extended for everyone, e. g. someone defined own labratory or local 
> class types.
>
> Shall I make a proposal for xml format?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/96#issuecomment-76540431>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by grodansparadis** [comment]
Will be in SQLite table
